// Condensed reference data for the assistant's system prompt.
// Mirrors src/data/destinations.ts and src/data/festivals.ts (frontend is the
// source of truth for full content — this is just enough for recommendations).

export const destinations = [
  { id: 'jamestown-ga-mashie', name: 'Jamestown & Ga Mashie', region: 'Greater Accra', category: 'Heritage', tagline: 'Historic Ga fishing district', rating: 4.6 },
  { id: 'kwame-nkrumah-mausoleum', name: 'Kwame Nkrumah Memorial Park', region: 'Greater Accra', category: 'Heritage', tagline: "Ghana's independence memorial", rating: 4.5 },
  { id: 'independence-square', name: 'Black Star Square', region: 'Greater Accra', category: 'Heritage', tagline: 'Independence Square & the Black Star Gate', rating: 4.4 },
  { id: 'labadi-beach', name: 'Labadi Beach', region: 'Greater Accra', category: 'Beach', tagline: "Accra's liveliest beach", rating: 4.3 },
  { id: 'manhyia-palace', name: 'Manhyia Palace Museum', region: 'Ashanti', category: 'Heritage', tagline: 'Seat of the Asantehene', rating: 4.6 },
  { id: 'lake-bosomtwe', name: 'Lake Bosomtwe', region: 'Ashanti', category: 'Nature', tagline: "Ghana's only natural lake", rating: 4.5 },
  { id: 'kejetia-market', name: 'Kejetia Market', region: 'Ashanti', category: 'Market', tagline: "One of West Africa's largest markets", rating: 4.2 },
  { id: 'bonwire-kente', name: 'Bonwire Kente Village', region: 'Ashanti', category: 'Market', tagline: 'Birthplace of kente cloth', rating: 4.4 },
  { id: 'wli-waterfalls', name: 'Wli Waterfalls', region: 'Volta', category: 'Nature', tagline: "Ghana's tallest waterfall", rating: 4.9 },
  { id: 'tafi-atome', name: 'Tafi Atome Monkey Sanctuary', region: 'Volta', category: 'Wildlife', tagline: 'Sacred mona monkey forest', rating: 4.5 },
  { id: 'mount-afadjato', name: 'Mount Afadjato', region: 'Volta', category: 'Adventure', tagline: "Ghana's highest peak", rating: 4.6 },
  { id: 'amedzofe', name: 'Amedzofe', region: 'Volta', category: 'Nature', tagline: "Ghana's highest village", rating: 4.5 },
  { id: 'sogakope', name: 'Sogakope', region: 'Volta', category: 'Nature', tagline: 'Riverside resort town on the Volta', rating: 4.4 },
  { id: 'cape-coast-castle', name: 'Cape Coast Castle', region: 'Central', category: 'Heritage', tagline: 'UNESCO World Heritage site', rating: 4.8 },
  { id: 'elmina-castle', name: 'Elmina Castle', region: 'Central', category: 'Heritage', tagline: 'Oldest European building in sub-Saharan Africa', rating: 4.7 },
  { id: 'kakum-canopy-walk', name: 'Kakum Canopy Walk', region: 'Central', category: 'Nature', tagline: 'Rainforest canopy walkway', rating: 4.7 },
  { id: 'anomabo-beach', name: 'Anomabo Beach', region: 'Central', category: 'Beach', tagline: 'Quiet fishing-town beach', rating: 4.5 },
  { id: 'hans-cottage-pond', name: 'Hans Cottage Pond', region: 'Central', category: 'Wildlife', tagline: 'Crocodile pond restaurant', rating: 4.3 },
  { id: 'assin-manso', name: 'Assin Manso Ancestral Slave River', region: 'Central', category: 'Heritage', tagline: 'Ancestral homecoming site', rating: 4.6 },
  { id: 'boti-falls', name: 'Boti Falls', region: 'Eastern', category: 'Nature', tagline: 'Twin waterfall in the Yilo Krobo hills', rating: 4.7 },
  { id: 'umbrella-rock', name: 'Umbrella Rock', region: 'Eastern', category: 'Nature', tagline: 'Natural rock overhang with valley views', rating: 4.5 },
  { id: 'aburi-botanical-gardens', name: 'Aburi Botanical Gardens', region: 'Eastern', category: 'Nature', tagline: 'Colonial-era gardens in the Akuapem hills', rating: 4.6 },
  { id: 'adomi-bridge', name: 'Adomi Bridge', region: 'Eastern', category: 'Adventure', tagline: "Ghana's iconic Volta River crossing", rating: 4.5 },
  { id: 'yendi-dagbon', name: 'Yendi — Seat of the Dagbon Kingdom', region: 'Northern', category: 'Heritage', tagline: 'Traditional capital of the Dagbon kingdom', rating: 4.3 },
  { id: 'mole-national-park', name: 'Mole National Park', region: 'Savannah', category: 'Wildlife', tagline: "Ghana's largest wildlife reserve", rating: 4.6 },
  { id: 'larabanga-mosque', name: 'Larabanga Mosque', region: 'Savannah', category: 'Heritage', tagline: 'Sudanese-style mud mosque', rating: 4.4 },
  { id: 'paga-crocodile-pond', name: 'Paga Crocodile Pond', region: 'Upper East', category: 'Wildlife', tagline: 'Sacred crocodile sanctuary', rating: 4.2 },
  { id: 'tongo-tengzug', name: 'Tongo-Tengzug Shrine Landscape', region: 'Upper East', category: 'Heritage', tagline: 'Sacred hillside shrines', rating: 4.5 },
  { id: 'wechiau-hippo-sanctuary', name: 'Wechiau Community Hippo Sanctuary', region: 'Upper West', category: 'Wildlife', tagline: 'Community-run hippo watching on the Black Volta', rating: 4.5 },
  { id: 'gambaga-escarpment', name: 'Gambaga Escarpment', region: 'North East', category: 'Nature', tagline: 'Dramatic sandstone escarpment and viewpoint', rating: 4.3 },
  { id: 'kyabobo-national-park', name: 'Kyabobo National Park', region: 'Oti', category: 'Wildlife', tagline: 'Remote mountain reserve on the Togo border', rating: 4.3 },
  { id: 'bui-national-park', name: 'Bui National Park', region: 'Bono', category: 'Wildlife', tagline: 'Black Volta wildlife reserve and dam', rating: 4.3 },
  { id: 'boabeng-fiema-sanctuary', name: 'Boabeng-Fiema Monkey Sanctuary', region: 'Bono East', category: 'Wildlife', tagline: 'Sacred monkey sanctuary between two villages', rating: 4.6 },
  { id: 'goaso-forest-reserve', name: 'Goaso Forest Reserve', region: 'Ahafo', category: 'Nature', tagline: 'Cocoa-country forest reserve', rating: 4.1 },
  { id: 'bia-national-park', name: 'Bia National Park', region: 'Western North', category: 'Wildlife', tagline: 'Untouched rainforest on the Ivorian border', rating: 4.4 },
  { id: 'nzulezu-stilt-village', name: 'Nzulezu Stilt Village', region: 'Western', category: 'Heritage', tagline: 'Village built entirely on stilts', rating: 4.7 },
  { id: 'busua-beach', name: 'Busua Beach', region: 'Western', category: 'Beach', tagline: "Ghana's surf town", rating: 4.6 },
  { id: 'ankasa-conservation', name: 'Ankasa Conservation Area', region: 'Western', category: 'Wildlife', tagline: 'Untouched rainforest reserve', rating: 4.4 },
  { id: 'cape-three-points', name: 'Cape Three Points', region: 'Western', category: 'Beach', tagline: "Ghana's southernmost tip", rating: 4.7 },
]

export const festivals = [
  { id: 'homowo', name: 'Homowo', region: 'Greater Accra', people: 'Ga people', dateLabel: 'Sat 23 – Sun 31 Aug 2026', tag: 'Harvest' },
  { id: 'asafotufiami', name: 'Asafotufiami', region: 'Greater Accra', people: 'Ada people', dateLabel: 'Sat 1 Aug 2026', tag: 'Warrior' },
  { id: 'akwasidae', name: 'Akwasidae', region: 'Ashanti', people: 'Asante people', dateLabel: 'Every 42 days', tag: 'Royal' },
  { id: 'hogbetsotso', name: 'Hogbetsotso', region: 'Volta', people: 'Anlo Ewe', dateLabel: 'Sat 1 Nov 2026', tag: 'Migration' },
  { id: 'aboakyer', name: 'Aboakyer', region: 'Central', people: 'Effutu people', dateLabel: 'First Sat of May', tag: 'Hunt' },
  { id: 'fetu-afahye', name: 'Fetu Afahye', region: 'Central', people: 'Oguaa people', dateLabel: 'First Sat of Sep', tag: 'Harvest' },
  { id: 'bakatue', name: 'Bakatue', region: 'Central', people: 'Edina people', dateLabel: 'First Tue of Jul', tag: 'Harvest' },
  { id: 'panafest', name: 'PANAFEST', region: 'Central', people: 'Pan-African diaspora', dateLabel: 'Biennial, late Jul – early Aug', tag: 'Diaspora' },
  { id: 'damba', name: 'Damba', region: 'Northern', people: 'Dagbon people', dateLabel: 'Follows the Islamic lunar calendar', tag: 'Royal' },
  { id: 'kobine', name: 'Kobine', region: 'Upper West', people: 'Dagaaba people', dateLabel: 'Late Sep, Lawra', tag: 'Harvest' },
  { id: 'kundum', name: 'Kundum', region: 'Western', people: 'Ahanta & Nzema people', dateLabel: 'Rolls Aug – Nov across towns', tag: 'Harvest' },
]
